name: Deploy Retype Docs

on:
  # Trigger the workflow on pushes to the 'main' branch
  push:
    branches:
      - main
  # Allow manual runs from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  build-and-deploy:
    # Use the latest stable Ubuntu runner environment
    runs-on: ubuntu-latest
    
    # Optional: Set permissions for the GITHUB_TOKEN if needed
    permissions:
      contents: write # Required to push to gh-pages branch

    steps:
      - name: âš™ï¸ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: ğŸ› ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ“¦ Install Dependencies
        run: npm install 

      - name: ğŸ“ Generate Markdown Files
        run: |
          node ./src/index.js

      - name: ğŸ“ Generate Markdown Files
        run: |
          cd ./docs
          npx retype build

      - name: ğŸ“¤ Push '.retype' directory to 'retype' branch
        # This is the core action for pushing the directory contents
        uses: cpina/github-push-action@main
        with:
          target: ".retype" 
          branch: "retype" 
          force: true 
          commit-message: Deploying to 'retype' from main branch
          author: Deploy Bot <actions@github.com>