name: Deploy Retype Docs

on:
  # Trigger the workflow on pushes to the 'main' branch
  push:
    branches:
      - main
  # Allow manual runs from the Actions tab in GitHub
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    # Use the latest stable Ubuntu runner environment
    runs-on: ubuntu-latest
    
    # Optional: Set permissions for the GITHUB_TOKEN if needed
    permissions:
      contents: write # Required to push to gh-pages branch

    steps:
      - name: âš™ï¸ Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: ğŸ› ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ“¦ Install Dependencies
        run: npm install 

      - name: ğŸ“ Generate Markdown Files
        run: |
          node ./src/index.js

      - name: "Retype Build"
        env:
          RETYPE_KEY: ${{ secrets.RETYPE_KEY }}
        run: |
          cd ./docs
          npx retype wallet --add=$RETYPE_KEY
          npx retype build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/.retype
          branch: 'retype'